import { glslDirFromUV, glslPickColor } from './preamble.js';

export const kentFrag = [
  "precision highp float;",
  "uniform vec3 kentGamma1[5];",
  "uniform vec3 kentGamma2[5];",
  "uniform float kentKappa[5];",
  "uniform float kentBeta[5];",
  "uniform float perClassThr[5];",
  "uniform vec3 classColors[5];",
  "uniform float isGradient;",
  "uniform float maxTrainScores[5];",
  "varying vec2 vUv;",
  glslDirFromUV,
  "void main() {",
  "  vec3 x = dirFromUV(vUv);",
  "  float s0, s1, s2, s3, s4;",
  "  {",
  "    float d1 = dot(kentGamma1[0], x); float d2 = dot(kentGamma2[0], x);",
  "    vec3 g3 = cross(kentGamma1[0], kentGamma2[0]); float d3 = dot(g3, x);",
  "    s0 = kentKappa[0] * d1 + kentBeta[0] * (d2*d2 - d3*d3);",
  "  }",
  "  {",
  "    float d1 = dot(kentGamma1[1], x); float d2 = dot(kentGamma2[1], x);",
  "    vec3 g3 = cross(kentGamma1[1], kentGamma2[1]); float d3 = dot(g3, x);",
  "    s1 = kentKappa[1] * d1 + kentBeta[1] * (d2*d2 - d3*d3);",
  "  }",
  "  {",
  "    float d1 = dot(kentGamma1[2], x); float d2 = dot(kentGamma2[2], x);",
  "    vec3 g3 = cross(kentGamma1[2], kentGamma2[2]); float d3 = dot(g3, x);",
  "    s2 = kentKappa[2] * d1 + kentBeta[2] * (d2*d2 - d3*d3);",
  "  }",
  "  {",
  "    float d1 = dot(kentGamma1[3], x); float d2 = dot(kentGamma2[3], x);",
  "    vec3 g3 = cross(kentGamma1[3], kentGamma2[3]); float d3 = dot(g3, x);",
  "    s3 = kentKappa[3] * d1 + kentBeta[3] * (d2*d2 - d3*d3);",
  "  }",
  "  {",
  "    float d1 = dot(kentGamma1[4], x); float d2 = dot(kentGamma2[4], x);",
  "    vec3 g3 = cross(kentGamma1[4], kentGamma2[4]); float d3 = dot(g3, x);",
  "    s4 = kentKappa[4] * d1 + kentBeta[4] * (d2*d2 - d3*d3);",
  "  }",
  "  int bestCI = -1;",
  "  float bestRatio = -100000.0;",
  "  float bestScore = 0.0;",
  "  if (s0 >= perClassThr[0]) { float r = s0 / max(perClassThr[0], 0.0000001); if (r > bestRatio) { bestCI = 0; bestRatio = r; bestScore = s0; } }",
  "  if (s1 >= perClassThr[1]) { float r = s1 / max(perClassThr[1], 0.0000001); if (r > bestRatio) { bestCI = 1; bestRatio = r; bestScore = s1; } }",
  "  if (s2 >= perClassThr[2]) { float r = s2 / max(perClassThr[2], 0.0000001); if (r > bestRatio) { bestCI = 2; bestRatio = r; bestScore = s2; } }",
  "  if (s3 >= perClassThr[3]) { float r = s3 / max(perClassThr[3], 0.0000001); if (r > bestRatio) { bestCI = 3; bestRatio = r; bestScore = s3; } }",
  "  if (s4 >= perClassThr[4]) { float r = s4 / max(perClassThr[4], 0.0000001); if (r > bestRatio) { bestCI = 4; bestRatio = r; bestScore = s4; } }",
  "  if (bestCI >= 0) {",
  glslPickColor,
  "    float alpha = 0.55;",
  "    if (isGradient > 0.5) {",
  "      float thr = perClassThr[0]; float mts = maxTrainScores[0];",
  "      if (bestCI == 1) { thr = perClassThr[1]; mts = maxTrainScores[1]; }",
  "      else if (bestCI == 2) { thr = perClassThr[2]; mts = maxTrainScores[2]; }",
  "      else if (bestCI == 3) { thr = perClassThr[3]; mts = maxTrainScores[3]; }",
  "      else if (bestCI == 4) { thr = perClassThr[4]; mts = maxTrainScores[4]; }",
  "      float t = (mts > thr + 0.0001) ? (bestScore - thr) / (mts - thr) : 1.0;",
  "      alpha = 0.01 + 0.74 * clamp(t, 0.0, 1.0);",
  "    }",
  "    gl_FragColor = vec4(color, alpha);",
  "  } else {",
  "    gl_FragColor = vec4(0.0);",
  "  }",
  "}"
].join("\n");
