import { glslDirFromUV, glslPickColor } from './preamble.js';

export const logitFrag = [
  "precision highp float;",
  "uniform vec3 classW[5];",
  "uniform float classB[5];",
  "uniform float threshold;",
  "uniform float maxTrainScore;",
  "uniform vec3 classColors[5];",
  "uniform int scoreMode;",
  "varying vec2 vUv;",
  glslDirFromUV,
  "void main() {",
  "  vec3 x = dirFromUV(vUv);",
  "  float l0 = dot(classW[0], x) + classB[0];",
  "  float l1 = dot(classW[1], x) + classB[1];",
  "  float l2 = dot(classW[2], x) + classB[2];",
  "  float l3 = dot(classW[3], x) + classB[3];",
  "  float l4 = dot(classW[4], x) + classB[4];",
  "  float maxL = l0; int bestCI = 0;",
  "  if (l1 > maxL) { maxL = l1; bestCI = 1; }",
  "  if (l2 > maxL) { maxL = l2; bestCI = 2; }",
  "  if (l3 > maxL) { maxL = l3; bestCI = 3; }",
  "  if (l4 > maxL) { maxL = l4; bestCI = 4; }",
  "  float score = 0.0;",
  "  if (scoreMode == 1) {",
  "    score = maxL;",
  "  } else if (scoreMode == 2) {",
  "    score = maxL + log(exp(l0 - maxL) + exp(l1 - maxL) + exp(l2 - maxL) + exp(l3 - maxL) + exp(l4 - maxL));",
  "  } else {",
  "    float e0 = exp(l0 - maxL); float e1 = exp(l1 - maxL); float e2 = exp(l2 - maxL);",
  "    float e3 = exp(l3 - maxL); float e4 = exp(l4 - maxL);",
  "    float sumE = e0 + e1 + e2 + e3 + e4;",
  "    float maxP = e0;",
  "    if (e1 > maxP) maxP = e1;",
  "    if (e2 > maxP) maxP = e2;",
  "    if (e3 > maxP) maxP = e3;",
  "    if (e4 > maxP) maxP = e4;",
  "    score = maxP / sumE;",
  "  }",
  "  if (score >= threshold) {",
  glslPickColor,
  "    float t = (maxTrainScore > threshold + 0.0001) ? (score - threshold) / (maxTrainScore - threshold) : 1.0;",
  "    float alpha = 0.01 + 0.74 * clamp(t, 0.0, 1.0);",
  "    gl_FragColor = vec4(color, alpha);",
  "  } else {",
  "    gl_FragColor = vec4(0.0);",
  "  }",
  "}"
].join("\n");
