import { glslDirFromUV, glslPickColor } from './preamble.js';

export const odinFrag = [
  "precision highp float;",
  "uniform vec3 classW[5];",
  "uniform float classB[5];",
  "uniform float odinT;",
  "uniform float odinEps;",
  "uniform float threshold;",
  "uniform float maxTrainScore;",
  "uniform vec3 classColors[5];",
  "varying vec2 vUv;",
  glslDirFromUV,
  "void main() {",
  "  vec3 x = dirFromUV(vUv);",
  "  float l0 = dot(classW[0], x) + classB[0];",
  "  float l1 = dot(classW[1], x) + classB[1];",
  "  float l2 = dot(classW[2], x) + classB[2];",
  "  float l3 = dot(classW[3], x) + classB[3];",
  "  float l4 = dot(classW[4], x) + classB[4];",
  "  float t0 = l0 / odinT; float t1 = l1 / odinT; float t2 = l2 / odinT;",
  "  float t3 = l3 / odinT; float t4 = l4 / odinT;",
  "  float maxT = t0;",
  "  if (t1 > maxT) maxT = t1; if (t2 > maxT) maxT = t2;",
  "  if (t3 > maxT) maxT = t3; if (t4 > maxT) maxT = t4;",
  "  float e0 = exp(t0 - maxT); float e1 = exp(t1 - maxT);",
  "  float e2 = exp(t2 - maxT); float e3 = exp(t3 - maxT); float e4 = exp(t4 - maxT);",
  "  float sumE = e0 + e1 + e2 + e3 + e4;",
  "  float p0 = e0/sumE; float p1 = e1/sumE; float p2 = e2/sumE;",
  "  float p3 = e3/sumE; float p4 = e4/sumE;",
  "  int yhat = 0; float maxP = p0;",
  "  if (p1 > maxP) { maxP = p1; yhat = 1; }",
  "  if (p2 > maxP) { maxP = p2; yhat = 2; }",
  "  if (p3 > maxP) { maxP = p3; yhat = 3; }",
  "  if (p4 > maxP) { maxP = p4; yhat = 4; }",
  "  vec3 wYhat = classW[0];",
  "  if (yhat == 1) wYhat = classW[1];",
  "  else if (yhat == 2) wYhat = classW[2];",
  "  else if (yhat == 3) wYhat = classW[3];",
  "  else if (yhat == 4) wYhat = classW[4];",
  "  vec3 wAvg = p0*classW[0] + p1*classW[1] + p2*classW[2] + p3*classW[3] + p4*classW[4];",
  "  vec3 grad = (wYhat - wAvg) / odinT;",
  "  vec3 sg = vec3(",
  "    grad.x >= 0.0 ? 1.0 : -1.0,",
  "    grad.y >= 0.0 ? 1.0 : -1.0,",
  "    grad.z >= 0.0 ? 1.0 : -1.0);",
  "  vec3 xp = normalize(x + odinEps * sg);",
  "  float l0p = dot(classW[0], xp) + classB[0];",
  "  float l1p = dot(classW[1], xp) + classB[1];",
  "  float l2p = dot(classW[2], xp) + classB[2];",
  "  float l3p = dot(classW[3], xp) + classB[3];",
  "  float l4p = dot(classW[4], xp) + classB[4];",
  "  float t0p = l0p/odinT; float t1p = l1p/odinT; float t2p = l2p/odinT;",
  "  float t3p = l3p/odinT; float t4p = l4p/odinT;",
  "  float maxTp = t0p;",
  "  if (t1p > maxTp) maxTp = t1p; if (t2p > maxTp) maxTp = t2p;",
  "  if (t3p > maxTp) maxTp = t3p; if (t4p > maxTp) maxTp = t4p;",
  "  float e0p = exp(t0p - maxTp); float e1p = exp(t1p - maxTp);",
  "  float e2p = exp(t2p - maxTp); float e3p = exp(t3p - maxTp); float e4p = exp(t4p - maxTp);",
  "  float sumEp = e0p + e1p + e2p + e3p + e4p;",
  "  float score = max(max(max(max(e0p, e1p), e2p), e3p), e4p) / sumEp;",
  "  int bestCI = 0; float bestE = e0p;",
  "  if (e1p > bestE) { bestE = e1p; bestCI = 1; }",
  "  if (e2p > bestE) { bestE = e2p; bestCI = 2; }",
  "  if (e3p > bestE) { bestE = e3p; bestCI = 3; }",
  "  if (e4p > bestE) { bestE = e4p; bestCI = 4; }",
  "  if (score >= threshold) {",
  glslPickColor,
  "    float t = (maxTrainScore > threshold + 0.0001) ? (score - threshold) / (maxTrainScore - threshold) : 1.0;",
  "    float alpha = 0.01 + 0.74 * clamp(t, 0.0, 1.0);",
  "    gl_FragColor = vec4(color, alpha);",
  "  } else {",
  "    gl_FragColor = vec4(0.0);",
  "  }",
  "}"
].join("\n");
