import { glslDirFromUV, glslPickColor } from './preamble.js';

export const rmdsFrag = [
  "precision highp float;",
  "uniform mat3 invCov;",
  "uniform vec3 classMeans[5];",
  "uniform vec3 globalMean;",
  "uniform float threshold;",
  "uniform float minTrainScore;",
  "uniform vec3 classColors[5];",
  "varying vec2 vUv;",
  glslDirFromUV,
  "float mahalDist2(vec3 x, vec3 mu) {",
  "  vec3 d = x - mu;",
  "  return dot(d, invCov * d);",
  "}",
  "void main() {",
  "  vec3 x = dirFromUV(vUv);",
  "  float d0 = mahalDist2(x, classMeans[0]);",
  "  float d1 = mahalDist2(x, classMeans[1]);",
  "  float d2 = mahalDist2(x, classMeans[2]);",
  "  float d3 = mahalDist2(x, classMeans[3]);",
  "  float d4 = mahalDist2(x, classMeans[4]);",
  "  float minD = d0; int bestCI = 0;",
  "  if (d1 < minD) { minD = d1; bestCI = 1; }",
  "  if (d2 < minD) { minD = d2; bestCI = 2; }",
  "  if (d3 < minD) { minD = d3; bestCI = 3; }",
  "  if (d4 < minD) { minD = d4; bestCI = 4; }",
  "  float bgDist = mahalDist2(x, globalMean);",
  "  float score = minD - bgDist;",
  "  if (score <= threshold) {",
  glslPickColor,
  "    float t = (abs(threshold - minTrainScore) > 0.0001) ? (threshold - score) / (threshold - minTrainScore) : 1.0;",
  "    float alpha = 0.01 + 0.74 * clamp(t, 0.0, 1.0);",
  "    gl_FragColor = vec4(color, alpha);",
  "  } else {",
  "    gl_FragColor = vec4(0.0);",
  "  }",
  "}"
].join("\n");
