import { glslDirFromUV, glslPickColor } from './preamble.js';

export const vimFrag = [
  "precision highp float;",
  "uniform vec3 classW[5];",
  "uniform float classB[5];",
  "uniform vec3 vimU0;",
  "uniform vec3 vimU1;",
  "uniform vec3 muAll;",
  "uniform float vimAlphaU;",
  "uniform float threshold;",
  "uniform float maxTrainScore;",
  "uniform vec3 classColors[5];",
  "varying vec2 vUv;",
  glslDirFromUV,
  "void main() {",
  "  vec3 x = dirFromUV(vUv);",
  "  float l0 = dot(classW[0], x) + classB[0];",
  "  float l1 = dot(classW[1], x) + classB[1];",
  "  float l2 = dot(classW[2], x) + classB[2];",
  "  float l3 = dot(classW[3], x) + classB[3];",
  "  float l4 = dot(classW[4], x) + classB[4];",
  "  vec3 xc = x - muAll;",
  "  vec3 proj = dot(xc, vimU0) * vimU0 + dot(xc, vimU1) * vimU1;",
  "  vec3 res = xc - proj;",
  "  float vLogit = vimAlphaU * length(res);",
  "  float maxL = l0;",
  "  if (l1 > maxL) maxL = l1; if (l2 > maxL) maxL = l2;",
  "  if (l3 > maxL) maxL = l3; if (l4 > maxL) maxL = l4;",
  "  if (vLogit > maxL) maxL = vLogit;",
  "  float score = maxL + log(exp(l0-maxL) + exp(l1-maxL) + exp(l2-maxL) + exp(l3-maxL) + exp(l4-maxL) + exp(vLogit-maxL));",
  "  int bestCI = 0; float bestL = l0;",
  "  if (l1 > bestL) { bestL = l1; bestCI = 1; }",
  "  if (l2 > bestL) { bestL = l2; bestCI = 2; }",
  "  if (l3 > bestL) { bestL = l3; bestCI = 3; }",
  "  if (l4 > bestL) { bestL = l4; bestCI = 4; }",
  "  if (score >= threshold) {",
  glslPickColor,
  "    float t = (maxTrainScore > threshold + 0.0001) ? (score - threshold) / (maxTrainScore - threshold) : 1.0;",
  "    float alpha = 0.01 + 0.74 * clamp(t, 0.0, 1.0);",
  "    gl_FragColor = vec4(color, alpha);",
  "  } else {",
  "    gl_FragColor = vec4(0.0);",
  "  }",
  "}"
].join("\n");
